## Lesson 4 - Conda, IPython, and Jupyter Notebooks



### Readings

* Geohackweek: [Introduction to Conda](https://geohackweek.github.io/Introductory/01-conda-tutorial/)

### Table of Contents

* [Installation](#install)
* [IPython and Jupyter](#ipython)
* [Python Syntax](#syntax)
* [Data Types](#types)
* [Control Structures](#control)
* [Version](#version)

<a id="install"></a>

### Installing Miniconda and working with Conda

_Conda is an open source package management system and environment management system for installing multiple versions of software packages and their dependencies and switching easily between them. It works on Linux, OS X and Windows, and was created for Python programs but can package and distribute any software._ -- <http://conda.pydata.org/docs/>

First, install Miniconda3: <http://conda.pydata.org/miniconda.html>. By default, environments you create will use Python 3, but you can specify Python 2 if required. To launch Conda: if you are using Windows, open the Anaconda Prompt (instead of PowerShell) from the Start menu; if you are using macOS or Linux, the conda command can be accessed from your Terminal.

Then, create a conda environment. Let's make an environment called `python3` for this class that includes Python 3 and Jupyter. 

```
conda create -n python3 python=3 jupyter
```

To activate the environment (Windows: `conda activate`):

```
source activate python3
```

To deactivate the environment (Windows: `conda deactivate`):

```
source deactivate
```

To delete an environment:

```
conda env remove -n myenv
```

After you activate your environment, you can install additional packages to that environment using `conda install`:

```
conda install pandas
```

If the package isn't available from conda, try `pip install`:

```
pip install tabview
```

List the environments on your system:

```
conda env list
```

List the packages in your current environment:

```
conda list
```

<a id="ipython"></a>

### IPython and Jupyter

IPython offers enhanced interactive Python shells with support for data visualization, distributed and parallel computation, and the browser-based Jupyter notebook. Jupyter notebook provides support for code, text, mathematical expressions, inline plots, and other rich media.

#### Python command-line interpreter

To open the Python interpreter, go to your terminal and type:

```
python
```

#### IPython command-line interpreter

To open the IPython interpreter, go to your terminal and type:

```
ipython
```

#### Jupyter (IPython) notebooks

To launch a Jupyter notebook, go to terminal and type:

```
source activate python3
jupyter notebook
```

Open up a new notebook, then check out **Help > User Interface Tour** and **Help > Keyboard Shortcuts**.

<a id="syntax"></a>

## Python Crash Course

In this tutorial we will cover some basic aspects of Python using IPython (Jupyter) notebooks. 

1. Syntax
2. Data types
3. Loops and control structures
4. numpy, scipy, math

### Syntax

In [1]:
2 + 2

4

In [2]:
x = 5
y = 2
x * y

10

In [3]:
x ** y

25

In [4]:
print('Hello, world!')

Hello, world!


In [5]:
print('%s raised to power of %s equals %s' % (x, y, x ** y))

5 raised to power of 2 equals 25


<a id="types"></a>

### Data Types

#### Booleans

'True' and 'False' have special meaning in Python.

In [6]:
a = True
b = False

In [7]:
a == True

True

In [8]:
b == True

False

In [9]:
a or b

True

In [10]:
a and b

False

#### Numbers: integers and floats

Numbers are pretty straightforward, especially in Python 3.

In [11]:
1 + 2

3

In [12]:
1.0 + 2.0

3.0

In [13]:
1 / 2

0.5

In [14]:
1.0 / 2.0

0.5

In [15]:
type(1)

int

In [16]:
type(1/2)

float

#### Strings

The next four data types -- strings, lists, tuples, arrays -- are all sequences.

Strings are sequences of characters.

In [17]:
s = 'Hello, world'

In [18]:
type(s)

str

In [19]:
s[0:4]

'Hell'

In [20]:
s + '!'

'Hello, world!'

In [21]:
s

'Hello, world'

In [22]:
s = s + '!'

In [23]:
s

'Hello, world!'

#### Lists

Lists are _mutable_ sequences of anything.

In [24]:
l = [0, 1, 1, 2, 3, 5, 8]

In [25]:
m = [5, 2, 'a', 'xxx', True, [0, 1]]

In [26]:
l[0:3]

[0, 1, 1]

In [27]:
m[4]

True

In [28]:
m[4] = False

In [29]:
m[4:]

[False, [0, 1]]

#### Tuples

Tuples are immutable sequences of anything (similar to lists except you can't change them).

In [30]:
n = (3, 5, 6)

In [31]:
n[0]

3

In [32]:
n[0] = 2

TypeError: 'tuple' object does not support item assignment

#### Arrays (numpy)

In [33]:
# Import modules to use
import math
import numpy as np

In [34]:
mylist = [0, 2, 4]
np.array(mylist)

array([0, 2, 4])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [37]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [39]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [40]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
np.random.rand()

0.7780764313091308

In [42]:
np.random.rand(5)

array([0.84943052, 0.21125752, 0.32220287, 0.0216243 , 0.0963807 ])

#### Sets

Sets are unordered collections of unique objects.

In [43]:
s1 = {'a', 'b', 'c'}
s2 = {'a', 'd', 'e'}

In [44]:
s1 & s2

{'a'}

In [45]:
s1 | s2

{'a', 'b', 'c', 'd', 'e'}

In [46]:
s3 = set(l)
s4 = set(m[0:2])

In [47]:
s3 & s4

{2, 5}

In [48]:
s3 | s4

{0, 1, 2, 3, 5, 8}

In [49]:
s3 - s4

{0, 1, 3, 8}

#### Dictionaries

Dictionaries or 'dicts' are hash tables, where a key points to a value.

In [50]:
d = {'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [51]:
d

{'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [52]:
d['name']

'John Doe'

In [53]:
d['zip'] = 92039

<a id="control"></a>

### Loops and Control Structures

#### Boolean and comparison operations

In [54]:
x = 5
(x < 6) and (x > 4)

True

In [55]:
x != 4

True

In [56]:
5 in [3, 4, 5]

True

In [57]:
'ell' in 'Hello'

True

In [58]:
len('Hello') >= 5

True

#### if tests

In [59]:
if 'd' in 'abc':
    print('Learn your alphabet.')
elif (2 + 2 == 5):
    print('Sometimes yes.')
else: 
    print('Nothing is true.')    

Nothing is true.


#### while loops

In [60]:
i = 0
while (i < 5):
    print(i)
    i += 1

0
1
2
3
4


In [61]:
i

5

#### for loops

In [62]:
for x in [0, 1, 2, 3, 4]:
    print(x**2)

0
1
4
9
16


<a id="version"></a>

### Determining Your Python Version

#### Method 1: sys

In [63]:
import sys

In [64]:
sys.version

'3.7.0 | packaged by conda-forge | (default, Aug 27 2018, 17:24:52) \n[Clang 6.1.0 (clang-602.0.53)]'

#### Method 2: platform

In [65]:
import platform

In [66]:
platform.python_version()

'3.7.0'

In [67]:
platform.version()

'Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64'

#### Method 3: version_information

In [68]:
# first install: pip install version_information
%reload_ext version_information
%version_information math, numpy, sys, platform

ModuleNotFoundError: No module named 'version_information'