### Answers to Assignment 5 - Regular Expressions

Complete the tasks below. Please turn in a single Jupyter notebook named `5_first_last.ipynb` (substitute your first and last name). Please run Kernel > Restart & Run All on your notebook before turning in.

#### Answer to A. Regular expressions in the command line

Setup: Download [`scripps_pier_20151110.csv`](https://github.com/cuttlefishh/python-for-data-analysis/blob/master/data/scripps_pier_20151110.csv) to your directory `~/sio209/data`, if you haven't already. You will use regular expressions to get information from the file.

1. Get all the rows with data from 11/10/15 using grep. How would you keep the header line also? (Hint: to get an "or", use `\|` in grep or `|` in egrep.) 
* Get all the rows where the third column (pressure) begins with a "3" using grep. (Hint: if you want to match a period `.` and not any character, you can escape it with `\.`.)
* Change the year "15" to "2015" using sed. (Reminder: sed syntax is `'sed s/find/replace/'`. Hint: if you want to match a forward slash in sed, you can escape it with a backslash like `\/`.)
* Copy your shell code (e.g., grep, sed) to a Markdown cell in your notebook.

In [1]:
!cat ../../data/scripps_pier_20151110.csv | grep "11/10/15"

11/10/15 1:42,22.307,3.712,33.199,19.95
11/10/15 1:35,22.311,3.588,33.201,19.94
11/10/15 1:29,22.305,3.541,33.2,19.95
11/10/15 1:23,22.323,3.463,33.2,19.95
11/10/15 1:17,22.316,3.471,33.199,19.95
11/10/15 1:11,22.315,3.476,33.198,19.95
11/10/15 1:05,22.31,3.448,33.199,19.96
11/10/15 0:59,22.316,3.377,33.2,19.99
11/10/15 0:53,22.311,3.338,33.2,20
11/10/15 0:47,22.322,3.325,33.201,20.01
11/10/15 0:41,22.311,3.344,33.2,20.04
11/10/15 0:35,22.311,3.217,33.201,20.05
11/10/15 0:29,22.307,3.265,33.199,20.08
11/10/15 0:23,22.32,3.22,33.197,20.09
11/10/15 0:17,22.322,3.211,33.199,20.08
11/10/15 0:11,22.323,3.134,33.197,20.09
11/10/15 0:05,22.315,3.018,33.197,20.09


In [2]:
!cat ../../data/scripps_pier_20151110.csv | egrep "11/10/15|Date"

Date,chl (ug/L),pres (dbar),sal (PSU),temp (C)
11/10/15 1:42,22.307,3.712,33.199,19.95
11/10/15 1:35,22.311,3.588,33.201,19.94
11/10/15 1:29,22.305,3.541,33.2,19.95
11/10/15 1:23,22.323,3.463,33.2,19.95
11/10/15 1:17,22.316,3.471,33.199,19.95
11/10/15 1:11,22.315,3.476,33.198,19.95
11/10/15 1:05,22.31,3.448,33.199,19.96
11/10/15 0:59,22.316,3.377,33.2,19.99
11/10/15 0:53,22.311,3.338,33.2,20
11/10/15 0:47,22.322,3.325,33.201,20.01
11/10/15 0:41,22.311,3.344,33.2,20.04
11/10/15 0:35,22.311,3.217,33.201,20.05
11/10/15 0:29,22.307,3.265,33.199,20.08
11/10/15 0:23,22.32,3.22,33.197,20.09
11/10/15 0:17,22.322,3.211,33.199,20.08
11/10/15 0:11,22.323,3.134,33.197,20.09
11/10/15 0:05,22.315,3.018,33.197,20.09


In [3]:
!cat ../../data/scripps_pier_20151110.csv | grep ".*,.*,3\..*,.*,.*"

11/10/15 1:42,22.307,3.712,33.199,19.95
11/10/15 1:35,22.311,3.588,33.201,19.94
11/10/15 1:29,22.305,3.541,33.2,19.95
11/10/15 1:23,22.323,3.463,33.2,19.95
11/10/15 1:17,22.316,3.471,33.199,19.95
11/10/15 1:11,22.315,3.476,33.198,19.95
11/10/15 1:05,22.31,3.448,33.199,19.96
11/10/15 0:59,22.316,3.377,33.2,19.99
11/10/15 0:53,22.311,3.338,33.2,20
11/10/15 0:47,22.322,3.325,33.201,20.01
11/10/15 0:41,22.311,3.344,33.2,20.04
11/10/15 0:35,22.311,3.217,33.201,20.05
11/10/15 0:29,22.307,3.265,33.199,20.08
11/10/15 0:23,22.32,3.22,33.197,20.09
11/10/15 0:17,22.322,3.211,33.199,20.08
11/10/15 0:11,22.323,3.134,33.197,20.09
11/10/15 0:05,22.315,3.018,33.197,20.09
11/9/15 23:59,22.319,3.031,33.198,20.08
11/9/15 23:53,22.327,3.118,33.199,20.11
11/9/15 23:41,22.328,3.014,33.198,20.16
11/9/15 23:29,22.336,3.013,33.194,20.17
11/9/15 23:23,22.337,3.011,33.194,20.16
11/9/15 20:17,22.402,3.061,33.206,20.07
11/9/15 20:05,22.409,3.065,33.204,20.05
11/9/15 19:59,22.412,3.159,33.203,20.04
11/9/15 19:53,22

In [4]:
!cat ../../data/scripps_pier_20151110.csv | sed 's/\/15/\/2015/'

Date,chl (ug/L),pres (dbar),sal (PSU),temp (C)
11/10/2015 1:42,22.307,3.712,33.199,19.95
11/10/2015 1:35,22.311,3.588,33.201,19.94
11/10/2015 1:29,22.305,3.541,33.2,19.95
11/10/2015 1:23,22.323,3.463,33.2,19.95
11/10/2015 1:17,22.316,3.471,33.199,19.95
11/10/2015 1:11,22.315,3.476,33.198,19.95
11/10/2015 1:05,22.31,3.448,33.199,19.96
11/10/2015 0:59,22.316,3.377,33.2,19.99
11/10/2015 0:53,22.311,3.338,33.2,20
11/10/2015 0:47,22.322,3.325,33.201,20.01
11/10/2015 0:41,22.311,3.344,33.2,20.04
11/10/2015 0:35,22.311,3.217,33.201,20.05
11/10/2015 0:29,22.307,3.265,33.199,20.08
11/10/2015 0:23,22.32,3.22,33.197,20.09
11/10/2015 0:17,22.322,3.211,33.199,20.08
11/10/2015 0:11,22.323,3.134,33.197,20.09
11/10/2015 0:05,22.315,3.018,33.197,20.09
11/9/2015 23:59,22.319,3.031,33.198,20.08
11/9/2015 23:53,22.327,3.118,33.199,20.11
11/9/2015 23:47,22.332,2.962,33.199,20.13
11/9/2015 23:41,22.328,3.014,33.198,20.16
11/9/2015 23:35,22.341,2.972,33.193,20.18
11/9/2015 23:29,22.336,3.013,33.194,20.17
11/

#### Answer to B. Regular expressions in Python

Setup: Import the `re` module.

1. Create a string variable with the value 'The quick brown fox jumps over the lazy dog'.
2. Use `re.match` or `re.search` to see if the string starts with 'The'.
3. Use `re.search` to find the first instance of a lowercase letter followed by an 'o'.
4. Use `re.findall` to find all instances of a lowercase letter followed by an 'o'.
5. Use `re.sub` to change the last word to an animal of your choice.

In [5]:
import re

In [6]:
s = 'The quick brown fox jumps over the lazy dog'

In [7]:
matchobj = re.match(r'The', s)
matchobj.group()

'The'

In [8]:
searchobj = re.search(r'[a-z]o', s)
searchobj.group()

'ro'

In [9]:
findobj = re.findall(r'[a-z]o', s)
findobj

['ro', 'fo', 'do']

In [10]:
re.sub(r'\w*$', 'whale', s)

'The quick brown fox jumps over the lazy whalewhale'

#### Answer to C. Numpy basics

1. Create an array of ten random floats ranging from 0 to 10. Create a second array of ten integers from 0 to 9. 
3. Use 'fancy indexing' with masks to find the values in your first array that are greater than their corresponding values in the second array (e.g., if the first element in array 1 is greater than the first element in array 2).

In [11]:
import numpy as np

In [12]:
x = np.random.rand(10) * 10
y = np.arange(10)

In [13]:
x

array([5.38492139, 7.30115743, 7.9164117 , 5.17483359, 9.02989914,
       2.46943523, 6.06048994, 5.79185622, 7.42187875, 6.165999  ])

In [14]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x > y

array([ True,  True,  True,  True,  True, False,  True, False, False,
       False])

In [16]:
x[x > y]

array([5.38492139, 7.30115743, 7.9164117 , 5.17483359, 9.02989914,
       6.06048994])

#### Answer to D. Pandas basics

1. Read in the csv file `scripps_pier_20151110.csv` as a Pandas DataFrame with the index as the Date column and the column headers from the first row of that file.
2. Print all the date/times from 11/10/15. (Hint: you can get the indexes from the DataFrame, convert it to a list, then iterate over that list (using a for loop or list comprehension), and then use `re.match` or `re.search`.)
3. Print all the rows from 11/10/15. (Hint: you can use your answer to the exercise you just did but use `.loc` indexing.)

In [17]:
import pandas as pd

##### Option 1 - Use a regular expression to search the date/times

In [18]:
df = pd.read_csv('../../data/scripps_pier_20151110.csv', index_col=0, header=0)

In [19]:
l = list(df.index)

In [20]:
[date for date in l if re.match(r'11/10/15', date)]

['11/10/15 1:42',
 '11/10/15 1:35',
 '11/10/15 1:29',
 '11/10/15 1:23',
 '11/10/15 1:17',
 '11/10/15 1:11',
 '11/10/15 1:05',
 '11/10/15 0:59',
 '11/10/15 0:53',
 '11/10/15 0:47',
 '11/10/15 0:41',
 '11/10/15 0:35',
 '11/10/15 0:29',
 '11/10/15 0:23',
 '11/10/15 0:17',
 '11/10/15 0:11',
 '11/10/15 0:05']

In [21]:
df.loc[[date for date in l if re.match(r'11/10/15', date)]]

chl (ug/L)  pres (dbar)  sal (PSU)  temp (C)
Date                                                       
11/10/15 1:42      22.307        3.712     33.199     19.95
11/10/15 1:35      22.311        3.588     33.201     19.94
11/10/15 1:29      22.305        3.541     33.200     19.95
11/10/15 1:23      22.323        3.463     33.200     19.95
11/10/15 1:17      22.316        3.471     33.199     19.95
11/10/15 1:11      22.315        3.476     33.198     19.95
11/10/15 1:05      22.310        3.448     33.199     19.96
11/10/15 0:59      22.316        3.377     33.200     19.99
11/10/15 0:53      22.311        3.338     33.200     20.00
11/10/15 0:47      22.322        3.325     33.201     20.01
11/10/15 0:41      22.311        3.344     33.200     20.04
11/10/15 0:35      22.311        3.217     33.201     20.05
11/10/15 0:29      22.307        3.265     33.199     20.08
11/10/15 0:23      22.320        3.220     33.197     20.09
11/10/15 0:17      22.322        3.211     33.199     20.08
11/10/15 0:11      22.323        3.134     33.197     20.09
11/10/15 0:05      22.315        3.018     33.197     20.09

##### Option 2 - Convert the index to a datetime index, then just index the date (works with or without .loc)

In [22]:
df.index = pd.to_datetime(df.index)

In [23]:
df['11/10/15']

chl (ug/L)  pres (dbar)  sal (PSU)  temp (C)
Date                                                             
2015-11-10 01:42:00      22.307        3.712     33.199     19.95
2015-11-10 01:35:00      22.311        3.588     33.201     19.94
2015-11-10 01:29:00      22.305        3.541     33.200     19.95
2015-11-10 01:23:00      22.323        3.463     33.200     19.95
2015-11-10 01:17:00      22.316        3.471     33.199     19.95
2015-11-10 01:11:00      22.315        3.476     33.198     19.95
2015-11-10 01:05:00      22.310        3.448     33.199     19.96
2015-11-10 00:59:00      22.316        3.377     33.200     19.99
2015-11-10 00:53:00      22.311        3.338     33.200     20.00
2015-11-10 00:47:00      22.322        3.325     33.201     20.01
2015-11-10 00:41:00      22.311        3.344     33.200     20.04
2015-11-10 00:35:00      22.311        3.217     33.201     20.05
2015-11-10 00:29:00      22.307        3.265     33.199     20.08
2015-11-10 00:23:00      22.320        3.220     33.197     20.09
2015-11-10 00:17:00      22.322        3.211     33.199     20.08
2015-11-10 00:11:00      22.323        3.134     33.197     20.09
2015-11-10 00:05:00      22.315        3.018     33.197     20.09

In [24]:
df.loc['11/10/15']

chl (ug/L)  pres (dbar)  sal (PSU)  temp (C)
Date                                                             
2015-11-10 01:42:00      22.307        3.712     33.199     19.95
2015-11-10 01:35:00      22.311        3.588     33.201     19.94
2015-11-10 01:29:00      22.305        3.541     33.200     19.95
2015-11-10 01:23:00      22.323        3.463     33.200     19.95
2015-11-10 01:17:00      22.316        3.471     33.199     19.95
2015-11-10 01:11:00      22.315        3.476     33.198     19.95
2015-11-10 01:05:00      22.310        3.448     33.199     19.96
2015-11-10 00:59:00      22.316        3.377     33.200     19.99
2015-11-10 00:53:00      22.311        3.338     33.200     20.00
2015-11-10 00:47:00      22.322        3.325     33.201     20.01
2015-11-10 00:41:00      22.311        3.344     33.200     20.04
2015-11-10 00:35:00      22.311        3.217     33.201     20.05
2015-11-10 00:29:00      22.307        3.265     33.199     20.08
2015-11-10 00:23:00      22.320        3.220     33.197     20.09
2015-11-10 00:17:00      22.322        3.211     33.199     20.08
2015-11-10 00:11:00      22.323        3.134     33.197     20.09
2015-11-10 00:05:00      22.315        3.018     33.197     20.09